[package]
name = "grimly"
version = "0.1.0"
authors = ["rsilva42 <rsilva@student.42.us.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
